const cars = [
  {id:'m4',brand:'BMW',model:'M4 Competition',color:'#b8d976',price:84900,hp:503,time:'3.8',type:'Coupe',tag:'THE MAIN CHARACTER',story:'Sharp lines. A soundtrack you feel in your chest. A little extra drama for your imaginary commute.'},
  {id:'amg',brand:'Mercedes-Benz',model:'AMG GT 63',color:'#b9bdc5',price:175900,hp:577,time:'3.1',type:'Coupe',tag:'AFTER-HOURS ENERGY',story:'Long hood, low stance, and an entrance that needs no introduction. Your weekend just got an upgrade.'},
  {id:'rs6',brand:'Audi',model:'RS 6 Avant',color:'#8b9dac',price:126600,hp:621,time:'3.3',type:'Wagon',tag:'PRACTICAL. ALLEGEDLY.',story:'Room for the groceries. Power for the daydream. The everyday car with absolutely extraordinary intentions.'},
  {id:'xc90',brand:'Volvo',model:'XC90 Ultra',color:'#d4c7ab',price:71900,hp:295,time:'6.4',type:'SUV',tag:'SCANDINAVIAN STATE OF MIND',story:'A quiet kind of luxury. Generous space, beautiful details, and an imaginary escape to somewhere peaceful.'},
  {id:'m8',brand:'BMW',model:'M8 Competition',color:'#8c7b9f',price:138800,hp:617,time:'3.0',type:'Coupe',tag:'THE GRAND ESCAPE',story:'For the long way home, the coastal road, and the kind of journey you wish would never end.'},
  {id:'etron',brand:'Audi',model:'RS e-tron GT',color:'#b47160',price:147100,hp:637,time:'3.1',type:'Electric',tag:'SILENT. NEVER SUBTLE.',story:'Electric energy with a grand touring soul. A bold silhouette for your next chapter.'}
];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const known=new Set(cars.map(c=>c.id));
function restore(key){try { const value=JSON.parse(localStorage.getItem(key)||'[]'); return new Set(Array.isArray(value)?value.filter(id=>known.has(id)):[]); } catch {return new Set();}}
let saved=restore('dd-saved'),garage=restore('dd-garage'),brand='All cars',onlySaved=false,garageMode=false;
function persist(){try{localStorage.setItem('dd-saved',JSON.stringify([...saved]));localStorage.setItem('dd-garage',JSON.stringify([...garage]));}catch{}}
// Local photographs with source and license details in photo-credits.html.
function carArt(car,hero=false){return `<img class="car-photo" src="./assets/cars/${car.id}.jpg" alt="${car.brand} ${car.model}" loading="${hero?'eager':'lazy'}" decoding="async" ${hero?'fetchpriority="high"':''}>`;}
document.querySelector('.hero-car').innerHTML=carArt(cars[0],true);
document.querySelector('#brands').innerHTML=['All cars',...new Set(cars.map(c=>c.brand))].map(b=>`<button data-brand="${b}" aria-pressed="${b===brand}" class="${b===brand?'active':''}">${b}</button>`).join('');
function render(){const query=document.querySelector('#search').value.trim().toLowerCase();const visible=cars.filter(c=>(brand==='All cars'||c.brand===brand)&&(!onlySaved||saved.has(c.id))&&(!garageMode||garage.has(c.id))&&`${c.brand} ${c.model} ${c.type}`.toLowerCase().includes(query));document.querySelector('#garage-count').textContent=garage.size;document.querySelector('#results').textContent=`${garageMode?'YOUR DREAM GARAGE · ':''}${visible.length} ${visible.length===1?'car':'cars'} to ${garageMode?'admire':'daydream about'} · Illustrative USD prices`;document.querySelector('#empty').hidden=visible.length>0;document.querySelector('#cars').innerHTML=visible.map(c=>`<article class="card"><div class="car-art">${carArt(c)}<span class="badge">${garage.has(c.id)?'IN YOUR DREAM GARAGE':c.tag}</span><button class="save ${saved.has(c.id)?'selected':''}" data-save="${c.id}" aria-label="${saved.has(c.id)?'Unsave':'Save'} ${c.brand} ${c.model}" aria-pressed="${saved.has(c.id)}">${saved.has(c.id)?'♥':'♡'}</button></div><div class="card-body"><span class="brand-name">${c.brand.toUpperCase()}</span><h3>${c.model}</h3><div class="specs"><span>${c.hp} hp</span><span>0–60 in ${c.time}s</span><span>${c.type}</span></div><div class="card-bottom"><div class="price">${money(c.price)}<small>Dream price · You pay $0</small></div><button class="view" data-view="${c.id}">Take a closer look →</button></div></div></article>`).join('');}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400);}
function save(id){saved.has(id)?saved.delete(id):saved.add(id);persist();render();toast(saved.has(id)?'Saved for your next daydream.':'Removed from favorites.');}
document.querySelector('#brands').addEventListener('click',e=>{const b=e.target.closest('[data-brand]');if(!b)return;brand=b.dataset.brand;garageMode=false;document.querySelectorAll('[data-brand]').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',el===b);});render();});
document.querySelector('#search').addEventListener('input',render);
document.querySelector('#saved-filter').addEventListener('click',e=>{onlySaved=!onlySaved;e.currentTarget.classList.toggle('active',onlySaved);e.currentTarget.setAttribute('aria-pressed',onlySaved);render();});
document.querySelector('#cars').addEventListener('click',e=>{const s=e.target.closest('[data-save]'),v=e.target.closest('[data-view]');if(s)save(s.dataset.save);if(v)showDetail(v.dataset.view);});
function showDetail(id){const c=cars.find(c=>c.id===id);document.querySelector('#detail-body').innerHTML=`${carArt(c)}<p class="eyebrow">${c.brand} · ${c.type}</p><h2>${c.model}</h2><p>${c.story}</p><div class="detail-specs"><span>${c.hp}<small>Horsepower</small></span><span>${c.time}s<small>0–60 mph</small></span><span>${money(c.price)}<small>Illustrative USD price</small></span></div><p>This is a simulated purchase. No payment, reservation, or vehicle delivery. Specifications are illustrative and vary by model year.</p><div class="dialog-actions"><button class="secondary" id="detail-save">${saved.has(id)?'♥ Saved':'♡ Save car'}</button><button class="primary" id="claim">${garage.has(id)?'Admire your keys →':'Get the imaginary keys →'}</button></div>`;document.querySelector('#detail-save').onclick=e=>{save(id);e.currentTarget.textContent=saved.has(id)?'♥ Saved':'♡ Save car';};document.querySelector('#claim').onclick=()=>{garage.add(id);persist();render();document.querySelector('#detail').close();document.querySelector('#celebration-body').innerHTML=`<div class="celebration"><div class="star">✦</div><p class="eyebrow" style="justify-content:center">WELCOME TO YOUR DREAM GARAGE</p><h2>The keys are yours.<br>In your imagination.</h2><p>Your ${c.brand} ${c.model} is waiting.<br>Amount paid: <strong>$0</strong>. Feeling: priceless.</p><button class="primary" id="see-garage">Admire my garage →</button></div>`;document.querySelector('#see-garage').onclick=()=>{document.querySelector('#celebration').close();openGarage();};document.querySelector('#celebration').showModal();};document.querySelector('#detail').showModal();}
function openGarage(){garageMode=true;brand='All cars';onlySaved=false;document.querySelector('#search').value='';document.querySelectorAll('[data-brand]').forEach(el=>{el.classList.toggle('active',el.dataset.brand===brand);el.setAttribute('aria-pressed',el.dataset.brand===brand);});document.querySelector('#saved-filter').classList.remove('active');document.querySelector('#saved-filter').setAttribute('aria-pressed','false');render();document.querySelector('#collection').scrollIntoView({behavior:'smooth'});if(!garage.size)toast('Your garage is waiting. Explore a car to claim its imaginary keys.');}
document.querySelector('#garage-nav').onclick=openGarage;document.querySelector('#closing-garage').onclick=openGarage;
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});
render();
